
super_ids = {
    'NORM':1,
    'CD':2,
    'MI':3,
    'HYP':4,
    'STTC':5,  
}

middl_ids = {
    'SR':0,
    'NORM':11,
    'LAFB\LPFB':21,
    'IRBBB':22,
    'ILBBB':23,
    'CLBBB':24,
    'CRBBB':25,
    '_AVB':26,
    'IVCB':27,
    'WPW':28,
    'AMI':31,
    'IMI':32,
    'LMI':33,
    'PMI':34,
    'LVH':41,
    'RVH':42,
    'LAO\LAE':43,
    'RAO\RAE':44,
    'SEHYP':45,
    'ISCA':51,
    'ISCI':52,
    'ISC_':53,
    'STTC':54,
    'NST_':55,
}

sub_ids = {
    'NORM': 111,
    'LAFB': 211,
    'LPFB': 222,
    'IRBBB': 221,
    'ILBBB': 231,
    'CLBBB': 241,
    'CRBBB': 251,
    '1AVB': 261,
    '2AVB': 262,
    '3AVB': 263,
    'IVCB': 271,
    'WPW': 281,
    'AMI': 311,
    'ASMI': 312,
    'ALMI': 313,
    'INJAS': 314,
    'INJAS': 315,
    'INHLA': 316,
    'IMI': 321,
    'ILMI': 322,
    'IPLMI': 323,
    'IPLMI': 324,
    'IPMI': 325,
    'INJIN': 326,
    'LMI': 331,
    'PMI': 341,
    'ISCAL': 511,
    'ISCAS': 512,
    'ISCLA': 513,
    'ISCAN': 514,
    'ISCI': 521,
    'ISC_': 531,
    'NDT': 541,
    'DIG': 542,
    'LNGQT': 543,
    'ANEUR': 544,
    'EL': 545,
    'NST_': 551,
    'SR': 'SR',
    'LVH': 411,
    'RVH': 421,
    'LAO\LAE': 431,
    'RAO\RAE': 441,
    'SEHYP': 451,
}

MI_trans_dict = {
    'AMI':'前壁心肌梗死',
        'ASMI':'前内侧壁心肌梗死',
        'ALMI':'前外侧壁心肌梗死',
        'INJAS':'前内侧导联心内膜下损伤',
        'INJAL':'前外侧导联心内膜下损伤',
        'INJLA':'侧导联心内膜下损伤',
    'IMI':'下壁心肌梗塞',
        'ILMI':'下外侧壁心肌梗死',
        'IPLMI':'下后外侧心肌梗死',
        'IPMI':'下后壁心肌梗死',
        'INJIN':'下壁导联心内膜下损伤',
        'INJIL':'下侧导联心内膜下损伤',
    'LMI':'侧位心肌梗死',
    'PMI':'后壁心肌梗塞',
    
    'ISCA':'前导联缺血', 
        'ISCAL':'前外侧导联缺血', 
        'ISCAS':'前间壁导联缺血', 
        'ISCLA':'侧导联缺血', 
        'ISCAN':'前导联缺血', 
    'ISCI':'下壁导联缺血', 
    'ISC_':'非特异性缺血', 
    'STTC':'ST-T改变', 
        'NDT':'非诊断性T异常', 
        'DIG':'洋地黄作用', 
        'LNGQT':'长QT间期', 
        'ANEUR':'与室壁瘤相符的ST-T改变', 
        'EL':'电解紊乱或药物', 
    'NST_':'非特异性ST段改变', 
    }

I_want_config = [
    'AMI','ASMI','ALMI','INJAS','INJAS','INHLA',
    'IMI','ILMI','IPLMI','IPLMI','IPMI','INJIN',
    'LMI',
    'PMI',
    'ISCAL','ISCAS','ISCLA','ISCAN',
    'ISCI',
    'ISC_',
    'NDT','DIG','LNGQT','ANEUR','EL',
    'NST_',
    'SR',
]

MI_config = {
    'AMI':['AMI','ASMI','ALMI','INJAS','INJAS','INHLA'],
    'IMI':['IMI','ILMI','IPLMI','IPLMI','IPMI','INJIN'],
    'LMI':['LMI'],
    'PMI':['PMI'],
}

CD_config = {
    'LAFB\LPFB':['LAFB','LPFB'],
    'IRBBB':['IRBBB'],
    'ILBBB':['ILBBB'],
    'CLBBB':['CLBBB'],
    'CRBBB':['CRBBB'],
    '_AVB':['1AVB','2AVB','3AVB'],
    'IVCB':['IVCB'],
    'WPW':['WPW'],
}

NORM_config = {'NORM':['NORM']}

HYP_config = {
    'LVH':['LVH'],
    'RVH':['RVH'],
    'LAO\LAE':['LAO\LAE'],
    'RAO\RAE':['RAO\RAE'],
    'SEHYP':['SEHYP'],
}

STTC_config = {
    'ISCA':['ISCAL','ISCAS','ISCLA','ISCAN'],
    'ISCI':['ISCI'],
    'ISC_':['ISC_'],
    'STTC':['NDT','DIG','LNGQT','ANEUR','EL'],
    'NST_':['NST_'],
}

scp_statements = {
    'NORM':NORM_config,
    'CD':CD_config,
    'MI':MI_config,
    'HYP':HYP_config,
    'STTC':STTC_config,
}

sub2super = {
    'NORM': 'NORM',
    'LAFB': 'CD',
    'LPFB': 'CD',
    'IRBBB': 'CD',
    'ILBBB': 'CD',
    'CLBBB': 'CD',
    'CRBBB': 'CD',
    '1AVB': 'CD',
    '2AVB': 'CD',
    '3AVB': 'CD',
    'IVCB': 'CD',
    'WPW': 'CD',
    'AMI': 'MI',
    'ASMI': 'MI',
    'ALMI': 'MI',
    'INJAS': 'MI',
    'INJAS': 'MI',
    'INHLA': 'MI',
    'IMI': 'MI',
    'ILMI': 'MI',
    'IPLMI': 'MI',
    'IPLMI': 'MI',
    'IPMI': 'MI',
    'INJIN': 'MI',
    'LMI': 'MI',
    'PMI': 'MI',
    'ISCAL': 'STTC',
    'ISCAS': 'STTC',
    'ISCLA': 'STTC',
    'ISCAN': 'STTC',
    'ISCI': 'STTC',
    'ISC_': 'STTC',
    'NDT': 'STTC',
    'DIG': 'STTC',
    'LNGQT': 'STTC',
    'ANEUR': 'STTC',
    'EL': 'STTC',
    'NST_': 'STTC',
    'SR': 'SR',
    'LVH': 'HYP',
    'RVH': 'HYP',
    'LAO\LAE': 'HYP',
    'RAO\RAE': 'HYP',
    'SEHYP': 'HYP',
}

sub2middle = {
    'NORM': 'NORM',
    'LAFB': 'LAFB\LPFB',
    'LPFB': 'LAFB\LPFB',
    'IRBBB': 'IRBBB',
    'ILBBB': 'ILBBB',
    'CLBBB': 'CLBBB',
    'CRBBB': 'CRBBB',
    '1AVB': '_AVB',
    '2AVB': '_AVB',
    '3AVB': '_AVB',
    'IVCB': 'IVCB',
    'WPW': 'WPW',
    'AMI': 'AMI',
    'ASMI': 'AMI',
    'ALMI': 'AMI',
    'INJAS': 'AMI',
    'INJAS': 'AMI',
    'INHLA': 'AMI',
    'IMI': 'IMI',
    'ILMI': 'IMI',
    'IPLMI': 'IMI',
    'IPLMI': 'IMI',
    'IPMI': 'IMI',
    'INJIN': 'IMI',
    'LMI': 'LMI',
    'PMI': 'PMI',
    'ISCAL': 'ISCA',
    'ISCAS': 'ISCA',
    'ISCLA': 'ISCA',
    'ISCAN': 'ISCA',
    'ISCI': 'ISCI',
    'ISC_': 'ISC_',
    'NDT': 'STTC',
    'DIG': 'STTC',
    'LNGQT': 'STTC',
    'ANEUR': 'STTC',
    'EL': 'STTC',
    'NST_': 'NST_',
    'SR': 'SR',
    'LVH': 'LVH',
    'RVH': 'RVH',
    'LAO\LAE': 'LAO\LAE',
    'RAO\RAE': 'RAO\RAE',
    'SEHYP': 'SEHYP',
}

# def find_classes(scp_class):
#     super_class, current_class, sub_class = None, None, None
#     for super_class in scp_statements.keys():
#         if 

# for sp in scp_statements.keys():
#     for c in scp_statements[sp].keys():
#         for sub in scp_statements[sp][c]:
#             print('\''+sub+'\''+':','\''+sp+'\',')

STE_ = {
    'qrs(t) abnormal':1,
    't abnormal':1,
    'qrs(t)':0.5,
    'qrs':0.5,
    }
